-- V11__add_review_table.sql (H2用)
BEGIN;

CREATE TABLE IF NOT EXISTS review (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    toilet_id BIGINT NOT NULL,
    nickname VARCHAR(100),
    rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_review_toilet
        FOREIGN KEY (toilet_id) REFERENCES toilet(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_review_toilet_id ON review (toilet_id);

COMMIT;