-- V18__add_toilet_feedback.sql (H2テスト用)
-- H2はインメモリで常に新規のため IF NOT EXISTS チェックを省略

BEGIN;

-- 1. toilet_feedback テーブル作成
CREATE TABLE IF NOT EXISTS toilet_feedback (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    toilet_id   BIGINT NOT NULL,
    feeling     VARCHAR(20) NOT NULL,
    issue_tags  VARCHAR(200),
    user_level  SMALLINT,
    created_at  TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_feedback_toilet FOREIGN KEY (toilet_id) REFERENCES toilet(id) ON DELETE CASCADE
);

-- 2. インデックス
CREATE INDEX IF NOT EXISTS idx_toilet_feedback_toilet_id_created_at
    ON toilet_feedback(toilet_id, created_at DESC);

-- 3. toiletテーブルへのカラム追加（H2は常に新規のため IF NOT EXISTS 省略）
ALTER TABLE toilet ADD COLUMN trust_score  DECIMAL(5,1);
ALTER TABLE toilet ADD COLUMN feedback_count INT NOT NULL DEFAULT 0;

COMMIT;
