-- V23: デイリークエスト用テーブル作成 (H2用)

CREATE TABLE daily_quests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quest_date DATE NOT NULL UNIQUE,
    quest_type_1 VARCHAR(30) NOT NULL,
    quest_type_2 VARCHAR(30) NOT NULL,
    quest_type_3 VARCHAR(30) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_quest_progress (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(128) NOT NULL REFERENCES users(id),
    quest_date DATE NOT NULL,
    slot INTEGER NOT NULL CHECK (slot BETWEEN 1 AND 3),
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    completed_at TIMESTAMP WITH TIME ZONE,
    UNIQUE (user_id, quest_date, slot)
);

CREATE INDEX idx_user_quest_progress_user_date
ON user_quest_progress (user_id, quest_date);
