-- V2__add_equipment_table.sql (H2用)
-- H2はDO $$ ... END $$（PL/pgSQL）非対応のため書き直し。
-- H2はインメモリで常に新規のため、IF NOT EXISTS チェックを省略しシンプルに記述。

BEGIN;

-- 1) equipment テーブル作成
CREATE TABLE IF NOT EXISTS equipment (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    toilet_id BIGINT NOT NULL,
    type      VARCHAR(50) NOT NULL,
    CONSTRAINT fk_equipment_toilet
      FOREIGN KEY (toilet_id) REFERENCES toilet(id) ON DELETE CASCADE
);

-- 2) ユニーク制約（H2は常に新規DBなので直接追加）
ALTER TABLE equipment
    ADD CONSTRAINT uq_equipment_toilet_type UNIQUE (toilet_id, type);

-- 3) 既存データ移行（V1でwheelchair/diaper/open24h列が存在するため動作する）
INSERT INTO equipment (toilet_id, type)
SELECT t.id, 'WHEELCHAIR' FROM toilet t
WHERE t.wheelchair = true
  AND NOT EXISTS (
    SELECT 1 FROM equipment e WHERE e.toilet_id = t.id AND e.type = 'WHEELCHAIR'
  );

INSERT INTO equipment (toilet_id, type)
SELECT t.id, 'DIAPER' FROM toilet t
WHERE t.diaper = true
  AND NOT EXISTS (
    SELECT 1 FROM equipment e WHERE e.toilet_id = t.id AND e.type = 'DIAPER'
  );

INSERT INTO equipment (toilet_id, type)
SELECT t.id, 'OPEN_24H' FROM toilet t
WHERE t.open24h = true
  AND NOT EXISTS (
    SELECT 1 FROM equipment e WHERE e.toilet_id = t.id AND e.type = 'OPEN_24H'
  );

COMMIT;