-- V1__init_schema.sql
BEGIN;
CREATE TABLE IF NOT EXISTS toilet (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    lat DOUBLE PRECISION NOT NULL,
    lng DOUBLE PRECISION NOT NULL,
    address VARCHAR(200),
    description VARCHAR(500),
    cleanliness INTEGER,
    facility_category VARCHAR(50),
    location_category VARCHAR(255),
    usage_conditions VARCHAR(255),
    atmosphere VARCHAR(255),
    public_use BOOLEAN,
    type_park BOOLEAN,
    type_station BOOLEAN,
    type_mall BOOLEAN,
    equipment TEXT,
    wheelchair BOOLEAN,
    diaper BOOLEAN,
    open24h BOOLEAN
);
COMMIT;
