-- V2__add_equipment_table.sql
-- Phase 2-1: Equipmentテーブル追加＆既存データ移行（PostgreSQL）
-- 対応: 古いPostgreSQLでも動くように IF NOT EXISTS（CONSTRAINT）を使わない

BEGIN;

-- 1) equipment テーブル作成（無ければ作る）
CREATE TABLE IF NOT EXISTS equipment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    toilet_id BIGINT NOT NULL,
    type VARCHAR(50) NOT NULL,
    CONSTRAINT fk_equipment_toilet
      FOREIGN KEY (toilet_id) REFERENCES toilet(id) ON DELETE CASCADE
);

-- 2) ユニーク制約（存在しなければ追加）
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'uq_equipment_toilet_type'
  ) THEN
    ALTER TABLE equipment
      ADD CONSTRAINT uq_equipment_toilet_type UNIQUE (toilet_id, type);
  END IF;
END $$;

-- 3) 既存データ移行（重複挿入防止）
INSERT INTO equipment (toilet_id, type)
SELECT t.id, 'WHEELCHAIR'
FROM toilet t
WHERE t.wheelchair = true
  AND NOT EXISTS (
    SELECT 1 FROM equipment e
    WHERE e.toilet_id = t.id AND e.type = 'WHEELCHAIR'
  );

INSERT INTO equipment (toilet_id, type)
SELECT t.id, 'DIAPER'
FROM toilet t
WHERE t.diaper = true
  AND NOT EXISTS (
    SELECT 1 FROM equipment e
    WHERE e.toilet_id = t.id AND e.type = 'DIAPER'
  );

INSERT INTO equipment (toilet_id, type)
SELECT t.id, 'OPEN_24H'
FROM toilet t
WHERE t.open24h = true
  AND NOT EXISTS (
    SELECT 1 FROM equipment e
    WHERE e.toilet_id = t.id AND e.type = 'OPEN_24H'
  );

COMMIT;
