package com.imatoilet.backend;

import org.h2.tools.RunScript;
import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.Test;

import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class ExternalIdentityMigrationTest {
    @Test
    void completeH2MigrationChainReachesVersion38AndEnforcesSchemaConstraints() throws Exception {
        String database = "jdbc:h2:mem:flyway_" + UUID.randomUUID() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1";

        var result = Flyway.configure()
                .dataSource(database, "sa", "")
                .locations("classpath:db/migration-h2")
                .load()
                .migrate();

        assertThat(result.targetSchemaVersion).hasToString("38");

        try (Connection connection = DriverManager.getConnection(database, "sa", "")) {
            assertThatThrownBy(() -> connection.createStatement().executeUpdate("""
                    INSERT INTO toilet (name, lat, lng, source_key, source_external_id)
                    VALUES ('partial', 35.0, 139.0, 'osm', NULL)
                    """))
                    .isInstanceOf(SQLException.class);

            try (var equipment = connection.createStatement().executeQuery(
                    "SELECT toilet_id, type FROM equipment LIMIT 1")) {
                assertThat(equipment.next()).isTrue();
                long toiletId = equipment.getLong("toilet_id");
                String type = equipment.getString("type");
                assertThatThrownBy(() -> connection.createStatement().executeUpdate(
                        "INSERT INTO equipment (toilet_id, type) VALUES (" + toiletId + ", '" + type + "')"))
                        .isInstanceOf(SQLException.class);
            }
        }
    }

    @Test
    void backfillsOnlyExactOsmUrlsKeepsNullRowsAndEnforcesUniqueness() throws Exception {
        String database = "jdbc:h2:mem:migration_" + UUID.randomUUID() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1";
        try (Connection connection = DriverManager.getConnection(database, "sa", "")) {
            connection.createStatement().execute("""
                    CREATE TABLE toilet (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      source VARCHAR(100),
                      source_url VARCHAR(2048)
                    )
                    """);
            connection.createStatement().executeUpdate("""
                    INSERT INTO toilet (source, source_url) VALUES
                      ('OpenStreetMap', 'https://www.openstreetmap.org/node/5291294596'),
                      ('osm', 'https://www.openstreetmap.org/way/123'),
                      ('osm', 'https://www.openstreetmap.org/way/124/'),
                      ('osm', 'https://www.openstreetmap.org/node/0123'),
                      ('OpenStreetMap', 'https://www.openstreetmap.org/node/not-numeric'),
                      ('other', NULL),
                      ('other-2', NULL)
                    """);

            try (var reader = new InputStreamReader(
                    getClass().getResourceAsStream("/db/migration-h2/V38__add_external_source_identity.sql"),
                    StandardCharsets.UTF_8)) {
                RunScript.execute(connection, reader);
            }

            try (var result = connection.createStatement().executeQuery("""
                    SELECT source, source_key, source_external_id FROM toilet ORDER BY id
                    """)) {
                result.next();
                assertThat(result.getString("source")).isEqualTo("OpenStreetMap");
                assertThat(result.getString("source_key")).isEqualTo("osm");
                assertThat(result.getString("source_external_id")).isEqualTo("node/5291294596");
                result.next();
                assertThat(result.getString("source_external_id")).isEqualTo("way/123");
                result.next();
                assertThat(result.getString("source_key")).isNull();
                result.next();
                assertThat(result.getString("source_key")).isNull();
                result.next();
                assertThat(result.getString("source_external_id")).isNull();
                result.next();
                assertThat(result.getString("source_external_id")).isNull();
                result.next();
                assertThat(result.getString("source_external_id")).isNull();
            }

            connection.createStatement().executeUpdate(
                    "INSERT INTO toilet (source, source_url) VALUES ('null-safe', NULL)");
            assertThatThrownBy(() -> connection.createStatement().executeUpdate("""
                    INSERT INTO toilet (source, source_key, source_external_id)
                    VALUES ('duplicate', 'osm', 'node/5291294596')
                    """))
                    .isInstanceOf(SQLException.class);
        }
    }
}
